// This file will contain the gRPC service implementations
// The actual service structs will be generated by tonic-build from the proto files

use tonic::{Request, Response, Status};

// Placeholder for the generated code
// pub mod savassan {
//     pub mod data_curator {
//         pub mod v1 {
//             tonic::include_proto!("savassan.data_curator.v1");
//         }
//     }
// }

// TODO: Implement the actual gRPC service when proto compilation is set up
pub struct DataCuratorGrpcServer {
    // use_cases: Arc<CurationUseCases>,
}

impl DataCuratorGrpcServer {
    pub fn new() -> Self {
        Self {}
    }
}
